import { Injectable } from '@angular/core';
import { IProducts } from '../interface/interface';

@Injectable({
  providedIn: 'root',
})
export class DataService {
  constructor() {}
  private products: IProducts[] = [
    {
      id: 1,
      name: 'hemp shoes',
      category: 'Shoes',
      description: 'Comfortable and eco-friendly hemp shoes.',
      price: 123,
      image: 'shoes2.png',
      type: 'm',
    },
    {
      id: 2,
      name: 'white T-Shirt',
      category: 'Clothes',
      description: 'Stylish and sustainable hemp shirt.',
      price: 123,
      image: 't-short.png',
      type: 'm',
    },
    {
      id: 3,
      name: 'Knitted bags',
      category: 'Bags',
      description: 'Durable and versatile hemp backpack.',
      price: 123,
      image: 'bag2.png',
      type: 'm',
    },
    {
      id: 4,
      name: 'Hemp Hat',
      category: 'Accessories',
      description: 'Eco-friendly and fashionable hemp hat.',
      price: 124,
      image: 'hat.png',
      type: 'm',
    },
    {
      id: 5,
      name: 'Hemp Wallet',
      category: 'Accessories',
      description: 'Compact and durable hemp wallet.',
      price: 19.99,
      image: 'walet.png',
      type: 'm',
    },
    {
      id: 6,
      name: 'Hemp Pants',
      category: 'Clothes',
      description: 'Comfortable and stylish hemp pants.',
      price: 59.99,
      image: 'f-pants.png',
      type: 'f',
    },
    {
      id: 7,
      name: 'Satchel Bag',
      category: 'Bags',
      description: 'Spacious and sturdy hemp tote bag.',
      price: 39.99,
      image: 'bag1.png',
      type: 'f',
    },
    {
      id: 8,
      name: 'Hemp Beanie',
      category: 'Accessories',
      description: 'Warm and soft hemp beanie.',
      price: 24.99,
      image: 'beanie.png',
      type: 'both',
    },
    {
      id: 9,
      name: 'One Piece',
      category: 'Clothes',
      description: 'Elegant and sustainable hemp dress.',
      price: 69.99,
      image: 'f-one-piece.png',
      type: 'f',
    },
    {
      id: 10,
      name: 'Hemp Scarf',
      category: 'Accessories',
      description: 'Soft and warm hemp scarf.',
      price: 34.99,
      image: '',
      type: 'both',
    },
    {
      id: 11,
      name: 'Hemp Sneakers',
      category: 'Shoes',
      description: 'Stylish and comfortable hemp sneakers.',
      price: 99.99,
      image: 'shoes1.png',
      type: 'm',
    },
    {
      id: 12,
      name: 'Hemp Jacket',
      category: 'Clothes',
      description: 'Warm and durable hemp jacket.',
      price: 129.99,
      image: '',
      type: 'both',
    },
    {
      id: 13,
      name: 'Hemp Messenger Bag',
      category: 'Bags',
      description: 'Functional and stylish hemp messenger bag.',
      price: 59.99,
      image: 'bag3.png',
      type: 'm',
    },
    {
      id: 14,
      name: 'Hemp Socks',
      category: 'Accessories',
      description: 'Comfortable and breathable hemp socks.',
      price: 14.99,
      image: '',
      type: 'both',
    },
    {
      id: 15,
      name: 'Hemp Skirt',
      category: 'Clothes',
      description: 'Chic and sustainable hemp skirt.',
      price: 54.99,
      image: '',
      type: 'f',
    },
    {
      id: 16,
      name: 'White Pointy-toe Heels',
      category: 'Shoes',
      description: 'Stylish and comfortable hemp sneakers.',
      price: 99.99,
      image: 'shoes3.png',
      type: 'both',
    },
    {
      id: 17,
      name: 'Hemp Tote Bag',
      category: 'Bags',
      description: 'Eco-friendly and spacious hemp tote bag.',
      price: 29.99,
      image: '',
      type: 'both',
    },
    {
      id: 18,
      name: 'Hemp Long Sleeve Shirt',
      category: 'Clothes',
      description: 'Comfortable and warm hemp long sleeve shirt.',
      price: 49.99,
      image: '',
      type: 'm',
    },
    {
      id: 19,
      name: 'Hemp Gym Shorts',
      category: 'Clothes',
      description: 'Breathable and flexible hemp gym shorts.',
      price: 34.99,
      image: '',
      type: 'm',
    },
    {
      id: 20,
      name: 'Hemp Crossbody Bag',
      category: 'Bags',
      description: 'Trendy and practical hemp crossbody bag.',
      price: 44.99,
      image: '',
      type: 'f',
    },
    {
      id: 21,
      name: 'Hemp Sandals',
      category: 'Shoes',
      description: 'Casual and comfortable hemp sandals.',
      price: 69.99,
      image: '',
      type: 'both',
    },
    {
      id: 22,
      name: 'Hemp Travel Backpack',
      category: 'Bags',
      description: 'Durable and spacious hemp travel backpack.',
      price: 89.99,
      image: '',
      type: 'm',
    },
    {
      id: 23,
      name: 'Hemp Winter Coat',
      category: 'Clothes',
      description: 'Warm and stylish hemp winter coat.',
      price: 159.99,
      image: '',
      type: 'both',
    },
    {
      id: 24,
      name: 'Hemp Sunglasses',
      category: 'Accessories',
      description: 'Fashionable hemp sunglasses with UV protection.',
      price: 39.99,
      image: '',
      type: 'both',
    },
    {
      id: 25,
      name: 'Hemp Keychain',
      category: 'Accessories',
      description: 'Handmade hemp keychain with a unique design.',
      price: 9.99,
      image: '',
      type: 'both',
    },
    {
      id: 26,
      name: 'Hemp Headband',
      category: 'Accessories',
      description: 'Comfortable and stylish hemp headband.',
      price: 19.99,
      image: '',
      type: 'f',
    },
    {
      id: 27,
      name: 'Hemp Laptop Sleeve',
      category: 'Accessories',
      description: 'Protective and eco-friendly hemp laptop sleeve.',
      price: 34.99,
      image: '',
      type: 'both',
    },
    {
      id: 28,
      name: 'Hemp Shorts',
      category: 'Clothes',
      description: 'Casual and comfortable hemp shorts.',
      price: 39.99,
      image: '',
      type: 'm',
    },
    {
      id: 29,
      name: 'Hemp V-neck T-shirt',
      category: 'Clothes',
      description: 'Soft and sustainable hemp V-neck t-shirt.',
      price: 29.99,
      image: '',
      type: 'm',
    },
    {
      id: 30,
      name: 'Hemp Wrap Skirt',
      category: 'Clothes',
      description: 'Elegant and adjustable hemp wrap skirt.',
      price: 59.99,
      image: '',
      type: 'f',
    },
    {
      id: 31,
      name: 'Hemp Bracelet',
      category: 'Accessories',
      description: 'Stylish hemp bracelet with a natural look.',
      price: 14.99,
      image: '',
      type: 'both',
    },
    {
      id: 32,
      name: 'Hemp Travel Pouch',
      category: 'Accessories',
      description: 'Convenient and eco-friendly hemp travel pouch.',
      price: 24.99,
      image: '',
      type: 'both',
    },
  ];

  getProducts(): IProducts[] {
    return this.products;
  }

  getProductsByCategory(category: string): IProducts[] {
    return this.products.filter((product) => product.category === category);
  }

  getProductsByType(type: string): IProducts[] {
    return this.products.filter(
      (product) => product.type === type || product.type === 'both'
    );
  }
}
